#!/bin/bash
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATE_TIME=$(date +"%Y-%m-%d %H:%M:%S")
source /etc/os-release
OS=$PRETTY_NAME

UPTIME=$(uptime -p)
CPU=$(lscpu | grep "Model Name" | cut -d ":" -f2  | sed "s/^ *//")
RAM=$(free -h | grep "Memory:" | awk "(print $2)")
DISKS=$ 
echo "System Report for $HOSTNAME generated by $USERNAME, on $DATE_TIME"
echo -e "\n"
echo "System Information"
echo "---------------"
echo "OS:
