#!/bin/bash


HOSTNAME=$(hostname) #It finds the hostname of the system

USERNAME=$(whoami) #Stores the current username of the host who is using the system

DATE_TIME=$(date +"%Y-%m-%d %H:%M:%S") #Stores the current date and time into a variable

source /etc/os-release #Contains and load the system information from the file

OS=$PRETTY_NAME #Stores PRETTY NAME(Operating system of Linux) into a variable



UPTIME=$(uptime -p) #Stores the system uptime into a variable

CPU=$(lscpu | grep "Model name" | cut -d ":" -f2  | sed "s/^ *//") #Stores the CPU information Name along with its model in a variable

RAM=$(lshw -C memory | grep "size" | head -1 | awk "{print \$2,\$3}") #Gets the RAM information and stores it in a variable

DISKS=$(lsblk -dn -e 7 -o MODEL,SIZE) #Displays the disks and its sizes in the system

VIDEO=$(lspci | grep -i VGA) #Gets the GPU/Video card information and stores it in a variable

GATEWAY=$(ip route | grep default |awk "{print \$3}") #Stores the gateway IP address and store in a variable

INTERFACE=$(ip route | grep default | awk "{print \$5}")  #It gets and stores the NI connected to the gateway

HOST_ADDRESS=$(ip -4 addr show "$INTERFACE" | grep "inet " | awk "{print \$2}" | cut -d "/" -f1) #Gets the stores the IP address of the interface from the command above

DNS=$(grep nameserver /etc/resolv.conf | head -1 | awk "{print $2}") #Stores the first DNS server listed in the file and stores it in a variable

DISK_SPACE=$(df -h --output=fstype,size) #Stores the available mounted disk into a variable

PROCESS_COUNT=$(ps -e | wc -l) #Counts the current running processes in th esystem

LOAD_AVERAGES=$(uptime |awk -F "load average: " "{print \$2}") #Stores the load average inside the variable

PORTS=$(ss -tuln |grep LISTEN | awk "{print $5}") #List all the listening ports and stores it in a variable

UFW_STATUS=$(sudo ufw status | head -1 | cut -d ":" -f2 | sed "s/^ *//")


cat <<EOF

System Report for $HOSTNAME generated by $USERNAME, on $DATE_TIME

System Information
-----------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM

Disk(s):
$DISKS

Video: $VIDEO
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS


System Status
-----------------------
Users Logged In: $USERNAME
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Listening Network Ports:  $PORTS
UFW Status: $UFW_STATUS
EOF
